io:
  workdir_root_path: /volumes/workdir
  musta_folder_name: musta
  inputs_root_path: /volumes/inputs
  output_folder_name: outputs
  log_folder_name: logs
  benchmark_folder_name: benchmarks
  detect_folder_name: detection
  classify_folder_name: classification
  interpret_folder_name: interpretation
  results_folder_name: results
  resources_root_name: /volumes/resources
  funcotator_folder_name: funcotator
  vep_folder_name: vep
  samples_file: /volumes/samples.yml
  temp_folder_path: /volumes/tmp

pipeline:
  url: https://github.com/solida-core/musta.git
  tag: v1.2.0.1
  name: musta
  branch: master
  workflow_folder_name: workflow
  config_folder_name: config
  snakefile: Snakefile
  config_file: config.yaml
  samples_file: samples.yaml
  report_file: report.html
  stats_file: stats.txt
  results_folder_name: results
  out_suffix:
    call: _somatic_filtered_selected.vcf.gz


demo:
  url: https://repolab.crs4.it/solida-core/test-data-somatic.git
  demo_root_path: /volumes/workdir/test-data
  data_folder_name: data
  bam_folder_name: bam
  maf_folder_name: maf
  resources_folder_name: resources
  reference_filename: chr22.fa
  bed_filename: chr22_testbed.bed
  germline_filename: somatic-b37_af-only-gnomad.raw.sites.ucsc.chr22.vcf
  exac_filename: somatic-b37_small_exac_common_3.ucsc.chr22.vcf
  dbsnp_filename: dbsnp.chr22.vcf.gz

resources:
  ftp:
    host: ftp.broadinstitute.org
    user: gsapubftp-anonymous
    path: bundle/funcotator
    filename: funcotator_dataSources.v1.7.20200521s.tar.gz

summary:
  folder_name: summary
  common_pass_variants_heatmap_filename: common_pass_variants_heatmap.png
  common_variants_counts_filename: common_variants_counts.tsv
  common_variants_mean_filename: common_variants_mean.tsv
  mean_pass_variants_plot_filename: mean_pass_variants_plot.png
  mean_pass_variants_filename: mean_pass_variants.tsv
  mean_runtime_for_each_variant_caller_plot_filename: mean_runtime_plot.png
  mean_runtime_for_each_variant_caller_filename: mean_runtime.tsv
  pass_variants_data_filename: pass_variants_data.json
  runtime_for_sample_and_variant_caller_filename: runtime_for_sample_and_variant_caller.png
  somatic_variants_for_sample_and_variant_caller_filename: somatic_variants_for_sample_and_variant_caller.png
  summary_for_each_sample_and_variant_caller_filename: summary_for_each_sample_and_variant_caller.tsv
  summary_for_each_sample_and_variant_annotator_filename: summary_for_each_sample_and_variant_annotator.tsv
  gene_summary_all_filename: gene_summary_all.tsv
  gene_summary_pass_filename: gene_summary_pass.tsv
  impact_summary_all_filename: impact_summary_all.tsv
  impact_summary_pass_filename: impact_summary_pass.tsv
  somatic_variants_for_sample_and_variant_annotator_filename: somatic_variants_for_sample_and_variant_annotator.png
  runtime_for_sample_and_variant_annotator_filename: runtime_for_sample_and_variant_annotator.png
  mean_runtime_for_each_variant_annotator_plot_filename: mean_runtime_plot.png
  mean_runtime_for_each_variant_annotator_filename: mean_runtime.tsv
  plots:
    plot_summary_for_each_sample_and_variant_caller:
      title: Somatic Variants for each Variant Caller and Sample
      labelx: Sample
      labely: Somatic Variants Count
      groupby: VARIANT CALLER
      x: SAMPLE
      y: PASS VARIANT COUNT
    plot_summary_for_each_sample_and_variant_annotator:
      title: Somatic Variants for each Variant Annotator and Sample
      labelx: Samples
      labely: Somatic Variants
      legend: Variant Annotator
      x: SAMPLE
      y: PASS VARIANT COUNT
      hue: VARIANT ANNOTATOR
      palette: Set2
      style: whitegrid
    plot_mean_pass_variants:
      title: Average Somatic Variants per Sample for each Variant Caller
      labelx: Variant Caller
      labely: Average Count Pass
      groupby: VARIANT CALLER
      field: PASS VARIANT COUNT
    plot_runtime_for_each_sample_and_variant_caller:
      title: Runtime for each Variant Caller and Sample
      labelx: Sample
      labely: Runtime (minutes)
      legend: Variant Caller
      x: SAMPLE
      y: RUNTIME (seconds)
      groupby: VARIANT CALLER
      palette: Set2
    plot_runtime_for_each_sample_and_variant_annotator:
      title: Runtime for each Variant Annotator and Sample
      labelx: Sample
      labely: Runtime (minutes)
      legend: Variant Annotator
      x: SAMPLE
      y: RUNTIME (seconds)
      groupby: VARIANT ANNOTATOR
      palette: Set2
    plot_mean_runtime_variant_callers:
      title: Average Runtime per Sample for each Variant Caller
      labelx: Variant Caller
      labely: Average Runtime (minutes)
      groupby: VARIANT CALLER
      field: RUNTIME (seconds)
      color: lightcoral
    plot_mean_runtime_variant_annotators:
      title: Average Runtime per Sample for each Variant Annotator
      labelx: Variant Annotator
      labely: Average Runtime (minutes)
      groupby: VARIANT ANNOTATOR
      field: RUNTIME (seconds)
      color: lightcoral
    plot_common_variants_heatmap:
      title: Common Somatic Variants among Variant Callers
      label: Variant Caller
      cmap: viridis



    
