io:
  workdir_root_path: /volumes/workdir
  musta_folder_name: musta
  inputs_root_path: /volumes/inputs
  output_folder_name: outputs
  log_folder_name: logs
  resources_root_name: /volumes/resources
  samples_file: /volumes/samples.yml
  temp_folder_path: /volumes/tmp

pipeline:
  url: https://repolab.crs4.it/solida-core/musta.git
  tag: v1.2.0.1
  name: musta
  branch: master
  workflow_folder_name: workflow
  config_folder_name: config
  snakefile: Snakefile
  config_file: config.yaml
  samples_file: samples.yaml
  report_file: report.html
  stats_file: stats.txt
  results_folder_name: results
  out_suffix:
    call: _somatic_filtered_selected.vcf.gz


demo:
  url: https://repolab.crs4.it/solida-core/test-data-somatic.git
  demo_root_path: /volumes/workdir/test-data
  data_folder_name: data
  bam_folder_name: bam
  maf_folder_name: maf
  resources_folder_name: resources
  reference_filename: chr22.fa
  bed_filename: chr22_testbed.bed
  germline_filename: somatic-b37_af-only-gnomad.raw.sites.ucsc.chr22.vcf
  exac_filename: somatic-b37_small_exac_common_3.ucsc.chr22.vcf
  dbsnp_filename: dbsnp.chr22.vcf.gz

resources:
  ftp:
    host: ftp.broadinstitute.org
    user: gsapubftp-anonymous
    path: bundle/funcotator
    filename: funcotator_dataSources.v1.7.20200521s.tar.gz
