io:
  workdir_root_path: /volumes/workdir
  musta_folder_name: musta
  inputs_root_path: /volumes/inputs
  output_folder_name: outputs
  log_folder_name: logs
  benchmark_folder_name: benchmarks
  detect_folder_name: detection
  classify_folder_name: classification
  interpret_folder_name: interpretation
  results_folder_name: results
  resources_root_name: /volumes/resources
  funcotator_folder_name: funcotator
  vep_folder_name: vep
  samples_file: /volumes/samples.yml
  temp_folder_path: /volumes/tmp

pipeline:
  url: https://github.com/solida-core/musta.git
  tag: v1.2.0.1
  name: musta
  branch: master
  workflow_folder_name: workflow
  config_folder_name: config
  snakefile: Snakefile
  config_file: config.yaml
  samples_file: samples.yaml
  report_file: report.html
  stats_file: stats.txt
  results_folder_name: results
  out_suffix:
    call: _somatic_filtered_selected.vcf.gz


demo:
  url: https://repolab.crs4.it/solida-core/test-data-somatic.git
  demo_root_path: /volumes/workdir/test-data
  data_folder_name: data
  bam_folder_name: bam
  maf_folder_name: maf
  resources_folder_name: resources
  reference_filename: chr22.fa
  bed_filename: chr22_testbed.bed
  germline_filename: somatic-b37_af-only-gnomad.raw.sites.ucsc.chr22.vcf
  exac_filename: somatic-b37_small_exac_common_3.ucsc.chr22.vcf
  dbsnp_filename: dbsnp.chr22.vcf.gz

resources:
  ftp:
    host: ftp.broadinstitute.org
    user: gsapubftp-anonymous
    path: bundle/funcotator
    filename: funcotator_dataSources.v1.7.20200521s.tar.gz

stats:
  folder_name: stats
  common_pass_variants_heatmap_filename: common_pass_variants_heatmap.png
  common_variants_counts_filename: common_variants_counts.tsv
  common_variants_mean_filename: common_variants_mean.tsv
  mean_pass_variants_plot_filename: mean_pass_variants_plot.png
  mean_pass_variants_filename: mean_pass_variants.tsv
  mean_runtime_for_each_variant_caller_plot_filename: mean_runtime_plot.png
  mean_runtime_for_each_variant_caller_filename: mean_runtime.png
  pass_variants_data_filename: pass_variants_data.json
  runtime_for_sample_and_variant_caller_filename: runtime_for_sample_and_variant_caller.png
  somatic_variants_for_sample_and_variant_caller_filename: somatic_variants_for_sample_and_variant_caller.png
  stats_for_each_sample_and_variant_caller_filename: stats_for_each_sample_and_variant_caller.tsv